//
// build.gradle in TeamCode
//

apply from: '../build.common.gradle'
apply from: '../build.dependencies.gradle'

android {
    namespace = 'org.firstinspires.ftc.teamcode'

    packagingOptions {
        jniLibs.useLegacyPackaging true
    }
}

repositories {
    mavenCentral()
    google()
    maven { url = 'https://maven.brott.dev/' }
}

dependencies {
    implementation project(':FtcRobotController')
    
    // ĐÃ XÓA DÒNG TFOD Ở ĐÂY ĐỂ TRÁNH XUNG ĐỘT
    
    implementation "com.acmerobotics.roadrunner:ftc:0.1.25"
    implementation "com.acmerobotics.roadrunner:core:1.0.1"
    implementation "com.acmerobotics.roadrunner:actions:1.0.1"
    implementation "com.acmerobotics.dashboard:dashboard:0.5.1"
}
